### ISSUE TITLE
Feature Request: Delete all workspaces, other workspaces and empty path workdpaces commands

### ISSUE THREAD

**Issue by MasouShizuka** [mehyaa/vscode-workspace-storage-cleanup#1]
1. Delete all workspaces command (like plugin "Clear Storage")
2. Delete other workspaces command (if can detect current workspace): 
    - If running this command in a workspace, then delete other workspaces' storage
    - If running this command in a single file, then delete all workspaces' storage
3. Delete empty path workdpaces commands (if can detect the existence of the path on the local pc):
    - Delete those workspaces whose folder path do not exist in the local pc

**Comment by mehyaa** [comment]
With v1.1.2 this should be covered up.

**Comment by MasouShizuka** [comment]
Thanks for updating.
It's very intuitive to operate in the plugin page, and the features are covered.

Also, could you provide the same command in the Command Palette?
Sometimes, using mouse is very inconvenient.
Hope the situation that press `ctrl+shift+p` and input the command like `clear missing workspace storage`.

By the way, `Toggle all` seems not work.
But it doesn't matter because it can be done by `Invert selection`.

**Comment by mehyaa** [comment]
Closing this and will track the commands for Command Palette with #9
