### ISSUE TITLE
performance improvements

### ISSUE THREAD

**Issue by j4k0xb** [mehyaa/vscode-workspace-storage-cleanup#10]
It takes over 2 minutes to list my ~200 workspaces (*without* the folder size).
Also careful with benchmarking: files are seemingly cached in memory by Linux (and other OS?) and can be read much faster for the second time.

With the folder size it would probably be hours since vscode somehow created a workspace in the root and home directory.

Ideas on how to improve it:
- `Promise.all` in `getWorkspacesAsync`
- instead of a loading animation until everything is done, render each path as soon as it's available
- analyze the file sizes in the background and update each entry separately in the UI when done

**Comment by mehyaa** [comment]
I was planning to change the webview html parts with another approach but I like your ideas are more.

Showing the workspace size seems unnecessary and expensive, maybe I'll change it to on demand per workspace.

**Comment by mehyaa** [comment]
With [v1.3.0](https://github.com/mehyaa/vscode-workspace-storage-cleanup/releases/tag/v1.3.0) most of your ideas are implemented and with separating the HTML and scripts of webview new feature can now be implemented more easily.
