### ISSUE TITLE
shift select

### ISSUE THREAD

**Issue by j4k0xb** [mehyaa/vscode-workspace-storage-cleanup#11]
Would be useful to select/unselect a whole range by clicking one checkbox as the start and hold shift when clicking on the end checkbox. The start can also be below the end.
This is commonly used in e.g. gmail, github, excel

**Comment by mehyaa** [comment]
I didn't make that before, maybe I'll get some help from someone interested but first I need to change the webview html management.

**Comment by mehyaa** [comment]
With [v1.4.0](https://github.com/mehyaa/vscode-workspace-storage-cleanup/releases/tag/v1.4.0) you should select rangee with Shift+Click 👍🏻
