### ISSUE TITLE
Expected ',' or ']' after array element in JSON at position 183 (line 7 column 49)

### ISSUE THREAD

**Issue by Daniel3711997** [mehyaa/vscode-workspace-storage-cleanup#14]
<img width="1252" alt="Screenshot 2024-09-24 at 10 58 05" src="https://github.com/user-attachments/assets/f12e126c-3074-4dd8-869b-861a80b559f7">

**Comment by Daniel3711997** [comment]
That is because the extension is trying to read the .workspace file which contains JSON but with comments and its not a valid JSON for JSON.parse

**Comment by mehyaa** [comment]
This should be fixed with [v1.6.1](https://github.com/mehyaa/vscode-workspace-storage-cleanup/releases/tag/v1.6.1)
