### ISSUE TITLE
How to use the extension

### ISSUE THREAD

**Issue by TBdt38** [mehyaa/vscode-workspace-storage-cleanup#6]
So, this is a basic question, but i dont understand how to run the extension. I dont see any new icon nor new menu related to the extension. On its page, there is nothing to execute too. Few lines to explain how to run would be helpfull. Thanks in advance!

**Comment by legerch** [comment]
To use this extension, use **command palette** of VsCode (usually via `ctrl + shift + p`) and search for `workspaces: cleanup storage`.  
Once selected, you will see an array with all workspaces parsed
